kind = "DojoModel"
class_hash = "0x38b8f854df62fe57319d49ace072e8db42461e2e2ecaf395f9ce6905e2cd037"
original_class_hash = "0x38b8f854df62fe57319d49ace072e8db42461e2e2ecaf395f9ce6905e2cd037"
abi = "manifests/dev/abis/base/models/dojo_starter_models_inventory_inventory.json"
name = "dojo_starter::models::inventory::inventory"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "item0_count"
type = "u8"
key = false

[[members]]
name = "item1_count"
type = "u8"
key = false

[[members]]
name = "item2_count"
type = "u8"
key = false

[[members]]
name = "item3_count"
type = "u8"
key = false

[[members]]
name = "trash"
type = "u8"
key = false
